<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>SharpInfer.Gpu</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpInfer.Core\SharpInfer.Core.csproj" />
  </ItemGroup>
</Project>
